name: Go

on:
  push:
    branches:
      - "main"
      - "staging"
      - "develop"

  pull_request:
    branches:
      - "main"
      - "staging"
      - "develop"

permissions:
  contents: read
  pull-requests: read

jobs:

  build:
    strategy:
      matrix:
        go: [ 1.18 ]
        os: [ ubuntu-latest ]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      # Setup Go
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      # Run vet on the code
      - name: Run vet
        run: |
          go vet ./...

      # Golang CI lint action
      - name: Check lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.29
          only-new-issues: true

      # Run testing on the code
      - name: Test
        run: go test -v -cover ./...
